NitorCreations/vault

- nodejs/lib/vaultClient.js
The parameters provided earlier didn't make any sense. This should be correct.
> Fix encoding usage when calling the crypto library

- python/n_vault/vault.py
According to http://wiki.laptop.org/go/Canonical_JSON:
> Whitespace is not permitted between tokens. Leading and trailing
> whitespace is likewise disallowed. The members production in object
> must consist of keys in lexicographically sorted order.
> Serialize JSON in canonical form

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/errors.rs
- rust/src/lib.rs
- rust/src/main.rs
Using `thiserror` and deriving most of the errors from libraries gives a nicer ergonomy for error handling.
example when trying lookup with missing credentials:
```shell
~/src/github/vault/rust (rust-lib-error-handling) » cargo run load testingtesting
Finished dev [unoptimized + debuginfo] target(s) in 0.11s
Running `target/debug/vault load testingtesting`
Error: DescribeStackError(ConstructionFailure(ConstructionFailure { source: SigningStageError { kind: MissingCredentials } }))
> implement error handling

- .github/workflows/black.yml
- python/n_vault/cli.py
- python/release.sh
- rust/Cargo.lock
- rust/README.md
- rust/src/cli.rs
- rust/src/lib.rs
- rust/src/main.rs
- Move Rust CLI related stuff from `main.rs` to a new `cli.rs` module
- Print help if no args or commands are given
- Rename `CfParams` to `CloudFormationParams`
- Reformat all Python arg definitions to be in same format for better readability (easier to see all the possible args)
> Separate cli module for rust

- .github/workflows/black.yml
- .github/workflows/cargo.yml
- .github/workflows/go.yml
- .github/workflows/isort.yml
- .github/workflows/pip.yml
- .github/workflows/ruff.yml
- .pre-commit-config.yaml
- rust/Cargo.lock
- rust/Cargo.toml
- rust/README.md
- rust/src/cli.rs
- rust/src/errors.rs
- rust/src/lib.rs
- rust/src/main.rs
- Add `AWS_REGION` env variable option 
- Simplify anyhow context usage
- Sort std imports and third-party crates separately
- Bump rust project version, first to 0.5.0 to match crates.io and then 0.6.0 due to new env variable option
- Update clap and some other dependencies
> Rust improvements

- rust/Cargo.lock
- rust/Cargo.toml
- rust/README.md
- rust/build.sh
- rust/install.sh
- rust/src/cli.rs
- rust/src/errors.rs
- rust/src/lib.rs
- rust/src/main.rs
- Use `colored` crate for handling ANSI colors instead of manually specifying codes
- Add a few missing long and short argument / command options
- `Describe` and `Info` options were doing the same thing, add region to info print with repurposed debug function
- `cli::exists` function takes a reference like other methods instead of moving the string
- Add usage to readme
- Use red color for error messages and tweak error texts to avoid repeating "Error: Error..."
- Simplify anyhow context usage
- Update all crate versions in cargo.toml
Usage changes:
New info option:
Error colors and text changes:
Old:
Colors can be disabled by setting `NO_COLOR=1`:
> Improve Rust vault color handling and cli options

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/cli.rs
- rust/src/errors.rs
- rust/src/lib.rs
- rust/src/main.rs
- rust/src/value.rs
- rust/src/vault.rs
- Refactor vault public interface for creating a new vault
- Add `prefix` option to match python vault
- Reorder some code, private functions after public functions
> rust: implement prefix option and refactor vault factory methods

- python/n_vault/__init__.py
- python/n_vault/cli.py
- python/n_vault/template.py
- python/n_vault/vault.py
Making a separate PR for my Python changes made when implementing the init and update for Rust.
- In Vault.py, put private functions and methods after public. Change helper functions to static methods inside Vault class.
- Encapsulate `STATIC_IV` as a static class member since it is not used outside the Vault class.
- Make `to_str` public since it is used in the cli
- Streamline vault initialization for `init` case and others
> Python vault refactoring and code organization

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/cli.rs
- rust/src/cloudformation.rs
- rust/src/errors.rs
- rust/src/lib.rs
- rust/src/main.rs
- rust/src/vault.rs
- Move CLI related stuff away from library
- All printing happens in CLI now
- Move cloudformation library methods to their own module and expose some publicly so can use them in CLI
- Reduce public visibility for internal library stuff to crate only
- Improve docstrings
> rust: properly separate cli from library in vault init

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/cli.rs
- rust/src/cloudformation.rs
- rust/src/lib.rs
- rust/src/vault.rs
Same fixes as for the init that I did not realize to do previously:
Separate CLI stuff from vault library, move prints to CLI side.
> Rust: Move vault update prints from library to cli

- rust/Cargo.lock
- rust/Cargo.toml
- rust/README.md
- rust/src/cli.rs
- rust/src/errors.rs
- rust/src/main.rs
- rust/src/value.rs
- rust/src/vault.rs
> rust: implement direct encrypt and decrypt to match python

- rust/src/cli.rs
- rust/src/value.rs
- Output direct encrypt result in base64 encoding
- Assume direct decrypt input is base64 encoded and try to decode
```console
➜  rust git:(rust/output-encrypted-base64) ./vault encrypt 'hello world!' -o out.txt
➜  rust git:(rust/output-encrypted-base64) ✗ cat out.txt
AQECAHgN/X7CNJJDsz+LAJDffTM2XHc91tXZLWmwH1WcrX1diAAAAGowaAYJKoZIhvcNAQcGoFswWQIBADBUBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDOR/Edj1mrkrfjS7NAIBEIAnZX7iCdgBgcsX8M6ligcaBT63I4hL8zmgDZBZNLn6Jc7+esdF+88f%            
➜  rust git:(rust/output-encrypted-base64) ✗ ./vault decrypt - < out.txt
hello world!%
➜  rust git:(rust/output-encrypted-base64) ✗ ./vault encrypt 'testing another string'
AQECAHgN/X7CNJJDsz+LAJDffTM2XHc91tXZLWmwH1WcrX1diAAAAHQwcgYJKoZIhvcNAQcGoGUwYwIBADBeBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLw1bzTmk5bcWslGBAIBEIAxJFGa …
```
> rust: output encrypted binary data always as base64

- .github/workflows/integration.yml
- rust/Cargo.lock
- rust/Cargo.toml
- rust/README.md
- rust/src/cli.rs
- rust/src/main.rs
- Add `-q` / `--quiet` flag to suppress all "unnecessary" prints, including errors. If an error happens, just exit with 1 without printing anything. Useful especially if using vault in scripts. The exception to this is `lookup` which will still obviously output to stdout if not specified alternatively... 
- Add command for generating shell completions. By default will output to stdout, with an optional `install` flag that will put the completetion to the correct place directly.
Example of quiet output with the recent `status` command:
This also changes the behaviour for `exists` to always exit with 1 in case the key does not exist:
```console
➜  rust git:(rust/quiet-mode) ./vault completion --help
Generate shell completion
Usage: vault {completion|--completion} [OPTIONS] <SHELL> …
```
> Rust: add quiet option and shell completion generation

- rust/Cargo.lock
- rust/Cargo.toml
- rust/README.md
- rust/src/args.rs
- rust/src/cli.rs
- rust/src/lib.rs
- rust/src/vault.rs
- Add `--profile` option for specifying AWS profile name to use
- Remove `--id` alias from Rust CLI since it is used differently in the Python version to override IAM id
- Rename `--vault-stack` argument name to `--vaultstack` to match Python version
- Make more short command options visible in the help text 
- Print prefix in vault info if not empty
Looked into implementing the `--id` and `--secret` options for manually specifying IAM id that the Python version has but the aws sdk really does not want you to do that manually, and you need to give token and expiration time too (though these can be `None`). Also, they will be automatically picked up from env variables so better to just let the aws config load handle that instead of having our own manual extra handling for that. The profile …
> Rust: add profile CLI option and match closer to Python version

- .github/workflows/integration.yml
- .github/workflows/pip.yml
- .github/workflows/ruff.yml
- .github/workflows/rust.yml
- Cargo.toml
- rust/build.sh
Turns out having a Rust workspace means the rust build `target` dir goes to the repo root
> fix path for github actions after rust workspace update

- .github/workflows/integration.yml
- .github/workflows/python-wheel.yml
- .gitignore
- Cargo.lock
- Cargo.toml
- python-pyo3/README.md
- python-pyo3/pyproject.toml
- python-pyo3/python/n_vault/__init__.py
- python-pyo3/python/n_vault/cli.py
- python-pyo3/python/n_vault/vault.py
- python-pyo3/src/lib.rs
- python-pyo3/uv.lock
- python/n_vault/__init__.py
- python/n_vault/vault.py
- python/pyproject.toml
- rust/src/args.rs
- rust/src/errors.rs
- rust/src/value.rs
- rust/src/vault.rs
Enable using python-pyo3 vault version as a python library. Adds wrappers for accessing most vault functions: 
`all`, `delete`, `delete_many`, `direct_encrypt`, `direct_decrypt`, `exists`, `list_all`, `lookup`, `store`, `init`, `update`, and `stack_status`
(Some of these are new compared to the old python version)
- Re-organize pyo3 package to match old python version: 
- rename `p_vault` to `n_vault`
- put Python CLI under `cli.py` and library in `vault.py`
- Add integration tests for Python library usage
- Update python readme with vault library usage instructions 
The `Vault` class in the new library is a dummy class that is only there to make the interface the same as before, so you can use it like before but it does not actually construct a vault instance:
```python
from n_vault …
```
> Python-pyo3: add library interface

- .github/workflows/integration.yml
- Cargo.lock
- Cargo.toml
- python-pyo3/python/n_vault/vault.py
- python-pyo3/src/lib.rs
- rust/src/value.rs
Change python library `lookup` to return bytes to match existing behaviour
New behaviour breaks existing code such as:
```shell
HOOK_URL, SLACK_CHANNEL, SLACK_CHANNEL_ID = vault.lookup(f"dev_carebot_secrets").decode("utf-8").split("!!!")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
```
> python-pyo3: return bytes from lookup to match previous version

- Cargo.lock
- Cargo.toml
- rust/src/errors.rs
- rust/src/vault.rs
Pasi noticed that we have some vault secrets that still use the old deprecated encryption type. These do not work in the new vault version.
Add a descriptive error for this case:
```console
➜  rust git:(rust-old-encryption) ./vault l amibakery.nitor.zone-ssh-hostkeys.sh
Error: Failed to look up key 'amibakery.nitor.zone-ssh-hostkeys.sh'
Caused by:
Deprecated encryption method for secret. Secret needs to be re-encrypted!
```
Also adds a separate error for S3 get when the key does not exists vs any other error:
```console
➜  rust git:(rust-old-encryption) ./vault l does-not-exist
Error: Failed to look up key 'does-not-exist'
Caused by:
Key does not exist in S3
```
> Rust: show separate error message for deprecated encryption type

- Cargo.lock
- Cargo.toml
- rust/src/args.rs
- rust/src/cli.rs
- rust/src/cloudformation.rs
- rust/src/errors.rs
When I was implementing the init and update commands for the rust vault, I needed to create multiple vault stacks for testing. Deleting all of these by having to go to the aws console was annoying and recently noticed I had forgotten to delete one of them, so adding CLI commands to list all vault stacks and delete a vault stack.
Repurposes the `status` command as `stack` and adds the stack list and delete as subcommands for that.
In action:
```console
➜  rust git:(list-destroy-stacks) ./vault -h
Encrypted AWS key-value storage utility
Usage: vault [OPTIONS] [COMMAND]
Commands:
all, -a, --all            List available secrets [aliases: a, list, ls]
completion, --completion  Generate shell completions
delete, -d, --delete      Delete an existing key from the store [aliases: d]
describe, …
```
> rust: vault stack list and delete

- python-pyo3/Cargo.toml
- python-pyo3/src/lib.rs
Hi @Esgrove, I was at the python meetup and after that I checked this repository.
The patch makes python-pyo3 use one static async runtime for the lifetime of the module, so it will improve performance at the price of negligible increase in memory usage.
The patch uses the Rust feature LazyLock which was introduced with 1.80, that's why the minimum rust version was set.
I haven't found any CI pipeline configuration so I'm not sure if this is acceptable. If you don't want to limit yourself to the rust version 1.80 I can implement the changes with the crate [lazy_static](https://crates.io/crates/lazy_static).
> python-pyo3: use static async runtime

- .github/workflows/integration.yml
- python-pyo3/pyproject.toml
- python-pyo3/python/n_vault/nitor_vault_rs.pyi
- python-pyo3/python/n_vault/vault.py
- python-pyo3/src/lib.rs
- Add `nitor_vault_rs.pyi` for typing info. This way IDEs / editors know about the Rust python library.
- Return Python dictionaries directly from Rust lib. `PyObject` is an alias for `Py<PyAny>`, but we know the result will always be a dict. (I did not know how to use this originally since a plain `PyResult<PyDict>` does not work)
- Add integration test case for stack status
Type hints working in PyCharm:
> PyO3: Add Python stub file for typing support
